/**
 * Compiles wasm/kernel.c and wasm/pow.c into src/core/wasm-bytes.ts, the
 * module as base64 (so the package stays one set of JS files, and the CDN
 * bundles stay single files). Needs clang with the wasm32 target and wasm-ld
 * (LLVM 17 or later). Run with `npm run build:wasm` after changing wasm/.
 *
 * The generated file records a hash of the C sources; a unit test fails when
 * the sources change without a rebuild.
 */
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const sources = ['wasm/kernel.c', 'wasm/pow.c'];
const dir = mkdtempSync(join(tmpdir(), 'bie-wasm-'));
const out = join(dir, 'kernel.wasm');
try {
  execFileSync(
    process.env.CLANG ?? 'clang',
    [
      '--target=wasm32',
      '-Os',
      '-msimd128',
      '-mnontrapping-fptoint',
      // Keep a * b + c as two roundings, like JS.
      '-ffp-contract=off',
      '-nostdlib',
      '-fno-builtin',
      '-Wall',
      '-Werror',
      '-Wl,--no-entry',
      '-Wl,--import-memory',
      '-Wl,--export=__heap_base',
      '-Wl,--strip-all',
      '-o',
      out,
      ...sources.map((s) => join(root, s)),
    ],
    { stdio: 'inherit' },
  );
  const bytes = readFileSync(out);
  writeFileSync(
    join(root, 'src/core/wasm-bytes.ts'),
    `// Generated by scripts/build-wasm.mjs from ${sources.join(', ')}. Do not edit.\n` +
      `/** Hash of the C sources this was built from (checked by test/unit/wasm.test.ts). */\n` +
      `export const WASM_SOURCE_HASH = '${sourceHash()}';\n` +
      `/** The compiled module (${bytes.length} bytes), base64. */\n` +
      `export const WASM_BASE64 =\n  '${bytes.toString('base64')}';\n`,
  );
  console.log(`src/core/wasm-bytes.ts: ${bytes.length} bytes of WebAssembly`);
} finally {
  rmSync(dir, { recursive: true, force: true });
}

function sourceHash() {
  const h = createHash('sha256');
  for (const s of sources) h.update(readFileSync(join(root, s), 'utf8').replace(/\r\n/g, '\n'));
  return h.digest('hex').slice(0, 16);
}
